---
logging.level:
  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: WARN
  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping: WARN
  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: WARN
